# Generated by Django 3.1 on 2020-08-21 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_uuid', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Collected Movie',
                'verbose_name_plural': 'Collected Movies',
                'db_table': 'collected_movie',
            },
        ),
        migrations.CreateModel(
            name='UserMovieCollection',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this should be treated as active. Unselect this instead of deleting.', verbose_name='active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'User Movie Collection',
                'verbose_name_plural': 'User Movie Collections',
                'db_table': 'user_movie_collection',
            },
        ),
    ]
